### ISSUE TITLE
Deposit amount can't be written

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/dx-docs#6]
Pre conditions:

- Being logged at Metamask
-Test on Staging

Steps to reproduce:
1- Enter https://dx.staging.gnosisdev.com
2- Choose a Token pair
3- Click on "Specify amount to deposit" CTA
4- Try to introduce a new amount to deposit
5- Observe

Expected result: 
You can add numbers in order to specify amount of tokens for the transaction.

Actual result:
Typing numbers won't affect the gap. 

Environment: 

Chrome/Firefox/Brave/Edge - Windows 10

**Comment by MicaelaPesado** [comment]
It also happens in https://dx.dev.gnosisdev.com/

**Comment by anxolin** [comment]
Note this issue is for dx-react. Move it there pls :) 

Thanks,

**Comment by damiandragobetzky** [comment]
I'm on that!
